let session=null,qIndex=0,score=0,correct=0,activeQuestions=[],activeGameDef=null,selectedChecks=new Set();const $=id=>document.getElementById(id);
async function api(action,payload={}){if(!API_URL||API_URL.includes("PASTE_"))throw new Error("API_URL is not set in config.js.");const res=await fetch(API_URL,{method:"POST",body:JSON.stringify({action,...payload})});return await res.json();}
function setFeedback(msg){$("feedback").textContent=msg;}
async function joinGame(){const name=$("playerName").value.trim().replace(/\s+/g," ");const week=$("weekSelect").value;const round=$("roundSelect").value;if(!name)return alert("Enter your name first.");try{const result=await api("joinGame",{name,week,releaseType:round});if(!result.ok){$("entryPanel").classList.remove("hidden");$("activeGamePanel").classList.add("hidden");alert(result.message||"You cannot join this round.");return;}const gameName=result.game;session={name,week,game:gameName,releaseType:round,redemption:round==="redemption",playId:result.playId};activeGameDef=GAME_BANK[gameName];activeQuestions=session.redemption?activeGameDef.redemptionQuestions:activeGameDef.questions;if(!activeQuestions||activeQuestions.length===0){alert("This game has no questions for this round.");return;}if(result.resume){qIndex=Math.min(result.progress.qIndex||0,activeQuestions.length-1);score=result.progress.score||0;correct=result.progress.correct||0;}else{qIndex=0;score=0;correct=0;}$("entryPanel").classList.add("hidden");$("activeGamePanel").classList.remove("hidden");$("gameStatus").textContent=`${result.statusText}: ${gameName}`;$("winnerRule").textContent=activeGameDef.prizeEligible&&!session.redemption?"Top player + prize points":"Top player tracked, no prize points";renderQuestion();await refreshLeaderboard();}catch(e){alert(e.message);}}
function renderQuestion(){const q=activeQuestions[qIndex];$("questionText").textContent=q.q;$("answers").innerHTML="";$("matchingBox").innerHTML="";$("typedAnswerBox").classList.add("hidden");$("matchingBox").classList.add("hidden");$("nextBtn").disabled=true;selectedChecks=new Set();setFeedback(`Current score: ${score}`);if(activeGameDef.type==="choice"){q.a.forEach((answer,i)=>{const btn=document.createElement("button");btn.className="answer-btn";btn.textContent=answer;btn.onclick=()=>answerQuestion(i===q.c,btn);$("answers").appendChild(btn);});}if(activeGameDef.type==="typed")$("typedAnswerBox").classList.remove("hidden");if(activeGameDef.type==="selectAll"){q.a.forEach((answer,i)=>{const btn=document.createElement("button");btn.className="answer-btn";btn.textContent=answer;btn.onclick=()=>{if(selectedChecks.has(i)){selectedChecks.delete(i);btn.classList.remove("correct");}else{selectedChecks.add(i);btn.classList.add("correct");}};$("answers").appendChild(btn);});const submit=document.createElement("button");submit.textContent="Submit Selected Answers";submit.onclick=submitSelectAll;$("answers").appendChild(submit);}if(activeGameDef.type==="matching"){$("matchingBox").classList.remove("hidden");const right=q.pairs.map(p=>p[1]).sort(()=>Math.random()-.5);q.pairs.forEach(pair=>{const row=document.createElement("div");row.className="match-row";const left=document.createElement("strong");left.textContent=pair[0];const sel=document.createElement("select");sel.dataset.correct=pair[1];sel.innerHTML=`<option value="">Choose match</option>`+right.map(r=>`<option value="${r}">${r}</option>`).join("");row.appendChild(left);row.appendChild(sel);$("matchingBox").appendChild(row);});const submit=document.createElement("button");submit.textContent="Submit Matching";submit.onclick=submitMatching;$("matchingBox").appendChild(submit);}}
function submitTyped(){const q=activeQuestions[qIndex];const guess=$("typedAnswer").value.trim().toLowerCase();if(!guess)return alert("Type an answer first.");answerQuestion(guess===q.answer.toLowerCase());$("typedAnswer").value="";}
function submitSelectAll(){const q=activeQuestions[qIndex];answerQuestion([...selectedChecks].sort().join(",")===[...q.c].sort().join(","));}
function submitMatching(){const selects=[...document.querySelectorAll("#matchingBox select")];answerQuestion(selects.every(sel=>sel.value&&sel.value===sel.dataset.correct));}
async function saveProgress(){if(!session)return;try{await api("saveProgress",{playId:session.playId,qIndex,score,correct});}catch(e){}}
function answerQuestion(isCorrect,clickedBtn){[...document.querySelectorAll(".answer-btn")].forEach(btn=>btn.disabled=true);if(clickedBtn)clickedBtn.classList.add(isCorrect?"correct":"wrong");if(isCorrect){score+=10;correct++;setFeedback(`Correct! Current score: ${score}`);}else setFeedback(`Not quite. Current score: ${score}`);$("nextBtn").disabled=false;saveProgress();}
async function nextQuestion(){qIndex++;await saveProgress();if(qIndex<activeQuestions.length)return renderQuestion();score+=5;try{const result=await api("submitScore",{playId:session.playId,name:session.name,week:session.week,game:session.game,releaseType:session.releaseType,score,correct,answered:activeQuestions.length,prizeEligible:activeGameDef.prizeEligible&&!session.redemption});$("questionText").textContent=result.message||`Game complete. Final score: ${score}`;$("answers").innerHTML="";$("typedAnswerBox").classList.add("hidden");$("matchingBox").classList.add("hidden");$("nextBtn").disabled=true;await refreshLeaderboard();}catch(e){alert(e.message);}}
function exitToEntry(){$("entryPanel").classList.remove("hidden");$("activeGamePanel").classList.add("hidden");saveProgress();}
async function refreshLeaderboard(){try{const result=await api("leaderboard",{});if(!result.ok)return;$("leaderboard").innerHTML="";result.leaderboard.forEach(row=>{const li=document.createElement("li");li.innerHTML=`<strong>${row.name}</strong> — ${row.totalPoints} pts<br><small>Prize points: ${row.prizePoints} • Games: ${row.gamesPlayed}</small>`;$("leaderboard").appendChild(li);});}catch(e){$("leaderboard").innerHTML=`<li>${e.message}</li>`;}}
function downloadCSV(filename,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const blob=new Blob([csv],{type:"text/csv"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
async function exportLeaderboard(code,outputId){const result=await api("exportLeaderboard",{code});if(!result.ok){if(outputId)$(outputId).textContent=JSON.stringify(result,null,2);else alert(result.message||"Export denied.");return;}downloadCSV("mhi_provider_coordinators_leaderboard.csv",result.rows);if(outputId)$(outputId).textContent="Leaderboard exported.";}
async function adminLogin(){const result=await api("adminVerify",{code:$("adminCode").value});if(result.ok)$("adminPanel").classList.remove("hidden");else alert("Invalid admin code.");}
async function ownerLogin(){const result=await api("ownerVerify",{code:$("ownerCode").value});if(result.ok)$("ownerPanel").classList.remove("hidden");else alert("Invalid owner code.");}
async function setRelease(role,status){const code=role==="owner"?$("ownerCode").value:$("adminCode").value;const week=role==="owner"?$("ownerWeek").value:$("adminWeek").value;const releaseType=role==="owner"?$("ownerReleaseType").value:$("adminReleaseType").value;const result=await api("setReleaseStatus",{role,code,week,releaseType,status});$(role==="owner"?"ownerOutput":"adminOutput").textContent=JSON.stringify(result,null,2);}
async function setWeekGame(role){const code=role==="owner"?$("ownerCode").value:$("adminCode").value;const week=role==="owner"?$("ownerWeek").value:$("adminWeek").value;const game=role==="owner"?$("ownerGameChoice").value:$("adminGameChoice").value;const result=await api("setWeekGame",{role,code,week,game});$(role==="owner"?"ownerOutput":"adminOutput").textContent=JSON.stringify(result,null,2);}
async function fairPlayAudit(){const result=await api("fairPlayAudit",{code:$("adminCode").value});$("adminOutput").textContent=JSON.stringify(result,null,2);}
async function ownerAdjust(){const result=await api("ownerAdjust",{code:$("ownerCode").value,name:$("adjustName").value,points:Number($("adjustPoints").value),reason:$("adjustReason").value});$("ownerOutput").textContent=JSON.stringify(result,null,2);await refreshLeaderboard();}
async function ownerAction(action){const result=await api(action,{code:$("ownerCode").value});$("ownerOutput").textContent=JSON.stringify(result,null,2);}
$("joinBtn").onclick=joinGame;$("submitTypedBtn").onclick=submitTyped;$("nextBtn").onclick=nextQuestion;$("exitBtn").onclick=exitToEntry;$("refreshBtn").onclick=refreshLeaderboard;$("exportBtn").onclick=()=>exportLeaderboard($("exportCode").value);$("adminLoginBtn").onclick=adminLogin;$("ownerLoginBtn").onclick=ownerLogin;$("adminSetGameBtn").onclick=()=>setWeekGame("admin");$("ownerSetGameBtn").onclick=()=>setWeekGame("owner");$("adminOpenBtn").onclick=()=>setRelease("admin","Open");$("adminCloseBtn").onclick=()=>setRelease("admin","Closed");$("ownerOpenBtn").onclick=()=>setRelease("owner","Open");$("ownerCloseBtn").onclick=()=>setRelease("owner","Closed");$("adminAuditBtn").onclick=fairPlayAudit;$("adminExportBtn").onclick=()=>exportLeaderboard($("adminCode").value,"adminOutput");$("ownerExportBtn").onclick=()=>exportLeaderboard($("ownerCode").value,"ownerOutput");$("ownerAdjustBtn").onclick=ownerAdjust;$("ownerGenerateTempBtn").onclick=()=>ownerAction("generateTempAdminCode");$("ownerLogsBtn").onclick=()=>ownerAction("getActionLogs");$("ownerSuspiciousBtn").onclick=()=>ownerAction("getSuspiciousActivity");$("ownerReportBtn").onclick=()=>ownerAction("internalSummaryReport");$("ownerParticipationBtn").onclick=()=>ownerAction("participationReport");$("ownerRedemptionBtn").onclick=()=>ownerAction("redemptionReport");$("ownerPrizeBtn").onclick=()=>ownerAction("prizePointsReport");$("ownerAuditBtn").onclick=()=>ownerAction("deepAuditReport");refreshLeaderboard();